### PR TITLE
feat: Add new regular data model synthesizer CWGANGP

### PR DESCRIPTION
**Pull request by jfsantos-ds**
Adds a Conditional Wasserstein GAN with Gradient Penalty, together with an example file.

This PR also:
- Fixes the column order in the sample method output of CGAN (label column was not being inserted in correct location)
- Simplifies the logic of label_col property setting (use a validation method instead of property setter with tuple args)

### CODE REVIEW

**Comment by jfsantos-ds** [comment]
The example file seems to fail in the load method, the stacktrace is the following:
```
Traceback (most recent call last):
  File "/home/fsantos/GitRepos/ydata-synthetic/examples/regular/cwgangp_example.py", line 75, in <module>
    synthesizer = model.load('cwgangp_synthtrained.pkl')
  File "/home/fsantos/GitRepos/ydata-synthetic/src/ydata_synthetic/synthesizers/gan.py", line 149, in load
    synth = load(path)
  File "/home/fsantos/miniconda3/envs/ydata_synth/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 585, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/fsantos/miniconda3/envs/ydata_synth/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "/home/fsantos/miniconda3/envs/ydata_synth/lib/python3.8/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/home/fsantos/miniconda3/envs/ydata_synth/lib/python3.8/pickle.py", line 1589, in load_reduce
    stack[-1] = func(*args)
TypeError: __new__() missing 1 required positional argument: 'feat_names_out'
ERROR conda.cli.main_run:execute(34): Subprocess for 'conda run ['python', '/home/fsantos/GitRepos/ydata-synthetic/examples/regular/cwgangp_example.py']' command failed.  (See above for error)
```
It seems related to the pickling of the processor.
Will leave this low priority fix for now.

**Comment by fabclmnt** [comment]
@jfsantos-ds naming and convention of the PR message

Also provide more detail. Suggestion: Add new model for regular data (etc)

"feat/message" shall be "feat: message"

**Review by fabclmnt — CHANGES_REQUESTED** [review]
Load error fix. 

Other than that nothing to add.

**Review by fabclmnt — APPROVED** [review]
🚀

**Pull request merged**
