### PR TITLE
chore: Showcase Gumbel-Softmax activation [SD-17]

### PR DESCRIPTION
**Pull request by jfsantos-ds**
This notebook introduces the Gumbel-Softmax activation feature and compares output from synthetic samples before and after the feature was added.

### CODE REVIEW

**Comment by jfsantos-ds** [comment]
Currently as draft because only the theoretical part has been finished so far and can be reviewed before the output comparison is added to the notebook (which should be more straightforward).

**Review by arunnthevapalan — APPROVED** [review]
Very well to the point! looks good to me.

**Review by fabclmnt — CHANGES_REQUESTED** [review]
Content needs to be more aligned to show-case if the potential impacts from Gumbel-Softmax.

**Review by fabclmnt — APPROVED** [review]
Good to go 🚀

**Pull request merged**
