### PR TITLE
chore: Streamlit demo app to generate synthetic dataset using ydata-synthetic on tabular data

### PR DESCRIPTION
**Pull request by rajeshai**
This streamlit demo application takes a pre-processed dataset as input.
Users can tweak the training parameters as desired and train a GAN model to generate a synthetic dataset.

### CODE REVIEW

**Comment by fabclmnt** [comment]
Hi @rajeshai can you please follow the PR naming and change you're Pr naming to "chore: (pr message description)"

**Comment by arunnthevapalan** [comment]
Hi @rajeshai - I already saw the demo, excellent work. Can I request you to make a ReadME.md file within this streamlit_app folder, explaining how someone can replicate your work? This would be extremely helpful since it comes under examples.

I had done something like this before with streamlit - please feel free to have a look at [this ReadME](https://github.com/arunnthevapalan/diabetes-prediction-app) for inspiration if you like. Adding the demo app link in this ReadMe will give you more visibility. :)

**Comment by rajeshai** [comment]
Hi @arunnthevapalan - I added the readme section. Please check it.

**Comment by fabclmnt** [comment]
Hi @rajeshai since v0.9 this app won't work with ydata-synthetic. 

There are a few changes request I would like to discuss with you. Let me know what is the best way for us to discuss that

**Comment by rajeshai** [comment]
Hi i sent you a connect request on LinkedIn. Please accept that. We can discuss.

**Pull request merged**
